// =============================================================================
// File Name = 'mp_ancient_final_tradespawns.gsc'
// Map Name = 'mp_ancient_final'
// =============================================================================
//
// This file was generated by the RotU admin development command 'Save Tradespawns'
//
// =============================================================================
//
// This file contains the tradespawns (equipment & weapon shop locations) for
// the map 'mp_ancient_final'
//
// N.B. You will need to delete the timecodes at the beginning of these lines!
//
load_tradespawns()
{
    level.tradespawns = [];
    
    level.tradespawns[0] = spawnstruct();  // spec'd for weapon shop
    level.tradespawns[0].origin = (4855.06,1207.83,16.7361);
    level.tradespawns[0].angles = (0.947845,90.9282,0);
    level.tradespawns[1] = spawnstruct();  // spec'd for equipment shop
    level.tradespawns[1].origin = (4841.06,581.282,16.7016);
    level.tradespawns[1].angles = (1.61113,90.6863,0);
    level.tradespawns[1].hudHeight = 85;
    level.tradespawns[2] = spawnstruct();  // spec'd for weapon shop
    level.tradespawns[2].origin = (2547.62,132.588,44.643);
    level.tradespawns[2].angles = (1.43051,183.68,0);
    level.tradespawns[3] = spawnstruct();  // spec'd for equipment shop
    level.tradespawns[3].origin = (2710.73,1700.4,15.9999);
    level.tradespawns[3].angles = (0,182.741,0);
    level.tradespawns[3].hudHeight = 85;
    level.tradespawns[4] = spawnstruct();  // spec'd for weapon shop
    level.tradespawns[4].origin = (-647.181,1566.86,15.9999);
    level.tradespawns[4].angles = (0,90.357,0);
    level.tradespawns[5] = spawnstruct();  // spec'd for equipment shop
    level.tradespawns[5].origin = (-671.733,673.125,16.0059);
    level.tradespawns[5].angles = (0.0159759,90.2527,0);
    level.tradespawns[5].hudHeight = 85;
    
    level.tradeSpawnCount = level.tradespawns.size;
}
